### USE THIS DOCUMENT TO CONFIGURE WHAT DEVICES YOU WANT TO ADD TO YOUR SETUP
## GUI WILL AUTO GENERATE BASED ON DEVICES LISTED HERE
DEBUG_MODE = True

## D E V I C E   D E F I N I T I O N
# RELAYS (FANS, VALVES, PUMPS, LIGHTS)
NAMES_RELAY	= ["12V Enable"," Q IN (0)", "Q WASTE (2)", "Q WATER (3)", "Q NUTR (4)", "Q OUT (5)", "FANS LAMP", "NC"]		# DISPLAY NAMES OF RELAYS
NR_RELAY 	= len(NAMES_RELAY)																# NR OF RELAYS

# VALVE CIRCUITS
NAMES_FLOW 		= ["WATER-INPUT", "NUTR.-INPUT", "OUTPUT-WASTE", "OUTPUT-INPUT"]		# DISPLAY NAMES OF FLOW CIRCUITS
VALVES_FLOW 	= [ [1,3], [1,4], [2,5], [1,5] ]										# LIST OF VALVE INDICES TO OPEN PER FLOW CIRCUIT [CIRUIT][VALVES]
FORCE_INTERLOCK = [True, True, False, False, True]										# FORCE PUMP INTERLOCK WHEN CERTAIN FLOW INDEX IS SELECTED, LAST INDEX IS FOR WHEN FLOW CIRCOUT IS DISABLED
NR_FLOW 		= len(NAMES_FLOW)														# NR OF FLOW CIRCUITS


# PWM DRIVEN LIGHTS
# NAMES_LAMP = 	[ "LAMP_NAME0", 	"LAMP_NAME1" ]										# DISPLAY NAME OF LAMP UNITS
# CHANNELS_LAMP = [ ['R','G','B','W'],	['B','G','R'] ]									# RGBW CHANNEL FOR EACH LAMP MODULE 	-> 2D-array [lamp][channel]
NAMES_LAMP 		= [ "LED0" ]																
CHANNELS_LAMP	= [ ['W'] ]									
NR_LAMP 		= len(NAMES_LAMP)														# NR OF CONTROLABLE LAMPS

# THERMAL SENSORS
NAMES_THERMO 	= ["TC0", "TC1"]														# DISPLAY NAMES OF THERMOCOUPLES
NR_THERMO 		= len(NAMES_THERMO)														# NR OF THERMOCOUPLES

# MOISTURE SENSORS
NAMES_MOISTURE 	= ["SOIL0"]																# DISPLAY NAMES OF ANALOG RESISTIVE MOISTURE SENSORS
NR_MOISTURE 	= len(NAMES_MOISTURE)													# NR OF ANALOG RESISTIVE MOISTURE SENSORS

# H-BRIDGE BASED PUMP (PWM, DIRECTION)
NAMES_PUMP	= ["PUMP0"]																	# PUMP DISPLAY NAMES
NR_PUMP 	= len(NAMES_PUMP)															# NUMBER OF PUMPS

# T I M I N G
PROGRAM_CYLCETIME	= 1000.0		#  CALL PROGRAM FUNCTION EVERY .. ms
ANI_CYCLETIME 		= 30000.0			#  UPDATE PLOT / CALL ANIMATION FUNCTION EVERY .. ms

# C O L O U R S
BG_MAIN		= '#7A7A7A'
BG_SUB 		= '#B0B0B0'
BG_SUBSUB	= '#DDDDDD'

