BG_MAIN = '#7A7A7A'
BG_SUB = '#B0B0B0'
BG_SUBSUB = '#DDDDDD'

PROGRAM_CYLCETIME= 1000.0		#  CALL PROGRAM FUNCTION EVERY .. ms
ANI_CYCLETIME = 5000			#  UPDATE PLOT / CALL ANIMATION FUNCTION EVERY .. ms

# DEVICES NAME & LENGTH DEFINITIONS
# RELAYS (FANS, VALVES, PUMPS, LIGHTS)
NAMES_RELAY = ["FANS LAMP", "Q OUT", "Q WATER", "Q NUTRIENT", "Q IN", "Q WASTE"]	# DISPLAY NAMES OF RELAYS
NR_RELAY = len(NAMES_RELAY)

# VALVE CIRCUITS
NAMES_FLOW = ["WATER-INPUT", "NUTR.-INPUT", "OUTPUT-WASTE", "OUTPUT-INPUT"]
VALVES_FLOW = [ [2,4], [3,4], [1,5], [1,4] ]
NR_FLOW = len(NAMES_FLOW)

# PWM DRIVEN LIGHTS
NAMES_LAMP = ["LED0"]
NR_LAMP = len(NAMES_LAMP)

# THERMAL SENSORS
NAMES_THERMO = ["TC0", "TC1"]
NR_THERMO = len(NAMES_THERMO)

# MOISTURE SENSORS
NAMES_MOISTURE = ["SOIL0"]
NR_MOISTURE = len(NAMES_MOISTURE)

# H-BRIDGE BASED PUMP (PWM, DIRECTION)
NAMES_PUMP = ["PUMP0"]
NR_PUMP = len(NAMES_PUMP)
